def yes_or_no(question):
    while "the answer is invalid":
        reply = str(input(question+' (y/n): ')).lower().strip()
        if reply[:1] == 'y':
            return True
        if reply[:1] == 'n':
            return False

def run(command,universal_newlines=True):
    cp = subprocess.run(
        command,
        universal_newlines=universal_newlines,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    if int(cp.returncode) > 0:
        log_error(f'ERROR({cp.returncode}): {cp.stderr}')
        sys.exit(cp.returncode)

    return(cp.stdout.strip())

def verify_bitbucket_repo_doesnt_exist(project_name,repo_name):
    try:
        repos = stash.projects[project_name].repos.list()
    except Exception as error:
        log_error(f'ERROR: Can\'t list bitbucket repos: {error}')
        sys.exit(20)

    if any(repo['name'] == repo_name for repo in repos):
        log_error(f'ERROR: A repository named {repo_name} already exists in the project named {project_name}!! Exiting.')
        sys.exit(25)

def create_new_bitbucket_repo(project_name,repo_name):
    message = f'Are you sure you want to create a new repo named {repo_name} in the project named {project_name}?'
    response = yes_or_no(f'🚀 {Style.BRIGHT}{message}{Style.RESET_ALL}')
    if not response == True:
        log_error("Exiting per user request not to continue")
        sys.exit(30)

    try:
        new_repo = stash.projects[project_name].repos.create(repo_name)
    except Exception as error:
        log_error(f'ERROR: creating bitbucket repo: {error}')
        sys.exit(40)

def init_local_git_repo(repo_name,git_url):
    run(["git", "init"])
    run(["git", "remote", "add", "origin", git_url])

# GIT
def add_and_commit():
    run(["git", "add", "--all"])
    run(["git", "-c", "commit.gpgsign=false", "commit", "-m", f'"Initial commit. Generated by cookiecutter-flask-api"'])

def push_branch_to_bitbucket(branch_name="master"):
    run(["git", "-c", "commit.gpgsign=false", "push", "--set-upstream", "origin", branch_name])

def fetch_origin():
    run(["git", "fetch", "origin"])